In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('global_conflicts_dataset.csv')
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Civilian_Deaths,Economic_Loss_USD_Billions,Temperature_Avg_C,...,Naval_Battles,Sanctions,Refugees_Millions,Ceasefire,Outcome,Latitude,Longitude,Climate_Zone,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,50364,176.45,8.2,...,104,Yes,6.68,No,Victory_A,88.811,101.020,Temperate,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,176846,435.83,24.8,...,87,Yes,14.51,Yes,Stalemate,55.878,78.502,Polar,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,17280,154.50,17.3,...,9,No,1.63,No,Stalemate,29.263,144.680,Tropical,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,92279,273.20,12.3,...,15,No,7.23,No,Victory_A,-22.281,-147.397,Polar,Water,No
4,Australia,France,War,2012,753,29149,40672,72545,351.35,31.1,...,22,Yes,19.65,No,Victory_A,17.638,169.360,Temperate,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,23016,465.44,4.1,...,162,Yes,10.62,No,Victory_A,71.175,36.407,Polar,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,175145,265.39,7.9,...,2,No,5.12,Yes,Victory_B,-42.396,-0.958,Polar,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,11370,461.47,21.5,...,32,No,2.47,No,Victory_A,-29.783,19.301,Arid,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,188963,103.94,31.2,...,6,No,7.26,No,Victory_A,81.474,42.923,Arid,NaN,No
2999,Israel,India,War,1999,285,20549,30400,65175,302.32,-6.1,...,104,Yes,8.58,Yes,Victory_A,-78.367,65.547,Arid,Oil,No

In [12]:
df = df.drop(columns=['Temperature_Avg_C'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Civilian_Deaths,Economic_Loss_USD_Billions,Rainfall_mm,...,Naval_Battles,Sanctions,Refugees_Millions,Ceasefire,Outcome,Latitude,Longitude,Climate_Zone,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,50364,176.45,2584.4,...,104,Yes,6.68,No,Victory_A,88.811,101.020,Temperate,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,176846,435.83,2379.0,...,87,Yes,14.51,Yes,Stalemate,55.878,78.502,Polar,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,17280,154.50,946.6,...,9,No,1.63,No,Stalemate,29.263,144.680,Tropical,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,92279,273.20,1065.6,...,15,No,7.23,No,Victory_A,-22.281,-147.397,Polar,Water,No
4,Australia,France,War,2012,753,29149,40672,72545,351.35,139.4,...,22,Yes,19.65,No,Victory_A,17.638,169.360,Temperate,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,23016,465.44,1558.8,...,162,Yes,10.62,No,Victory_A,71.175,36.407,Polar,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,175145,265.39,2851.2,...,2,No,5.12,Yes,Victory_B,-42.396,-0.958,Polar,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,11370,461.47,1948.2,...,32,No,2.47,No,Victory_A,-29.783,19.301,Arid,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,188963,103.94,832.4,...,6,No,7.26,No,Victory_A,81.474,42.923,Arid,NaN,No
2999,Israel,India,War,1999,285,20549,30400,65175,302.32,1594.6,...,104,Yes,8.58,Yes,Victory_A,-78.367,65.547,Arid,Oil,No

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('global_conflicts_dataset.csv')
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Civilian_Deaths,Economic_Loss_USD_Billions,Temperature_Avg_C,...,Naval_Battles,Sanctions,Refugees_Millions,Ceasefire,Outcome,Latitude,Longitude,Climate_Zone,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,50364,176.45,8.2,...,104,Yes,6.68,No,Victory_A,88.811,101.020,Temperate,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,176846,435.83,24.8,...,87,Yes,14.51,Yes,Stalemate,55.878,78.502,Polar,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,17280,154.50,17.3,...,9,No,1.63,No,Stalemate,29.263,144.680,Tropical,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,92279,273.20,12.3,...,15,No,7.23,No,Victory_A,-22.281,-147.397,Polar,Water,No
4,Australia,France,War,2012,753,29149,40672,72545,351.35,31.1,...,22,Yes,19.65,No,Victory_A,17.638,169.360,Temperate,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,23016,465.44,4.1,...,162,Yes,10.62,No,Victory_A,71.175,36.407,Polar,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,175145,265.39,7.9,...,2,No,5.12,Yes,Victory_B,-42.396,-0.958,Polar,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,11370,461.47,21.5,...,32,No,2.47,No,Victory_A,-29.783,19.301,Arid,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,188963,103.94,31.2,...,6,No,7.26,No,Victory_A,81.474,42.923,Arid,NaN,No
2999,Israel,India,War,1999,285,20549,30400,65175,302.32,-6.1,...,104,Yes,8.58,Yes,Victory_A,-78.367,65.547,Arid,Oil,No

In [ ]:
df = df.drop(columns=['Temperature_Avg_C','Economic_Loss_USD_Billions', 'Temperature_Avg_C', 'Latitude', 'Longitude', 'Climate_Zone'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Civilian_Deaths,Rainfall_mm,Terrain_Type,...,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Refugees_Millions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,50364,2584.4,Desert,...,Regional,Mixed,87,104,Yes,6.68,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,176846,2379.0,Plains,...,NATO,Conventional,1529,87,Yes,14.51,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,17280,946.6,Mountain,...,NaN,Nuclear,3239,9,No,1.63,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,92279,1065.6,Plains,...,NATO,Cyber,3185,15,No,7.23,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,72545,139.4,Plains,...,NATO,Mixed,12,22,Yes,19.65,No,Victory_A,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,23016,1558.8,Desert,...,NATO,Mixed,2073,162,Yes,10.62,No,Victory_A,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,175145,2851.2,Plains,...,Regional,Conventional,3077,2,No,5.12,Yes,Victory_B,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,11370,1948.2,Forest,...,Regional,Mixed,3212,32,No,2.47,No,Victory_A,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,188963,832.4,Plains,...,Regional,Cyber,3813,6,No,7.26,No,Victory_A,NaN,No
2999,Israel,India,War,1999,285,20549,30400,65175,1594.6,Urban,...,NaN,Conventional,1050,104,Yes,8.58,Yes,Victory_A,Oil,No

In [6]:
df = df.drop(columns=['Civilian_Deaths', 'Rainfall_mm', 'Terrain_Type', 'Refugees_Millions'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Population_A_Millions,Population_B_Millions,GDP_A_Billions,...,Alliance_A,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,1113.4,724.2,4887.9,...,NATO,Regional,Mixed,87,104,Yes,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,571.6,507.0,10851.5,...,NATO,NATO,Conventional,1529,87,Yes,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,677.0,1145.0,12079.9,...,Regional,NaN,Nuclear,3239,9,No,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,1303.8,98.1,12583.3,...,NaN,NATO,Cyber,3185,15,No,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,938.3,386.3,23875.5,...,Regional,NATO,Mixed,12,22,Yes,No,Victory_A,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,79.3,1333.6,21103.6,...,Regional,NATO,Mixed,2073,162,Yes,No,Victory_A,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,958.2,672.6,19243.5,...,Regional,Regional,Conventional,3077,2,No,Yes,Victory_B,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,875.8,1025.3,12157.5,...,Regional,Regional,Mixed,3212,32,No,No,Victory_A,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,946.4,793.9,2976.7,...,Regional,Regional,Cyber,3813,6,No,No,Victory_A,NaN,No
2999,Israel,India,War,1999,285,20549,30400,366.4,287.6,24253.0,...,NATO,NaN,Conventional,1050,104,Yes,Yes,Victory_A,Oil,No

In [7]:
df = df.drop(columns=['Population_A_Millions', 'Population_B_Millions', 'GDP_A_Billions'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,GDP_B_Billions,Alliance_A,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,15609.5,NATO,Regional,Mixed,87,104,Yes,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,12932.3,NATO,NATO,Conventional,1529,87,Yes,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,22137.4,Regional,NaN,Nuclear,3239,9,No,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,10539.7,NaN,NATO,Cyber,3185,15,No,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,14095.4,Regional,NATO,Mixed,12,22,Yes,No,Victory_A,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,12922.5,Regional,NATO,Mixed,2073,162,Yes,No,Victory_A,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,22966.5,Regional,Regional,Conventional,3077,2,No,Yes,Victory_B,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,4743.8,Regional,Regional,Mixed,3212,32,No,No,Victory_A,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,3134.9,Regional,Regional,Cyber,3813,6,No,No,Victory_A,NaN,No
2999,Israel,India,War,1999,285,20549,30400,6039.6,NATO,NaN,Conventional,1050,104,Yes,Yes,Victory_A,Oil,No

In [8]:
df = df.drop(columns=['GDP_B_Billions'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Alliance_A,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,NATO,Regional,Mixed,87,104,Yes,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,NATO,NATO,Conventional,1529,87,Yes,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,Regional,NaN,Nuclear,3239,9,No,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,NaN,NATO,Cyber,3185,15,No,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,Regional,NATO,Mixed,12,22,Yes,No,Victory_A,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,Regional,NATO,Mixed,2073,162,Yes,No,Victory_A,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,Regional,Regional,Conventional,3077,2,No,Yes,Victory_B,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,Regional,Regional,Mixed,3212,32,No,No,Victory_A,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,Regional,Regional,Cyber,3813,6,No,No,Victory_A,NaN,No
2999,Israel,India,War,1999,285,20549,30400,NATO,NaN,Conventional,1050,104,Yes,Yes,Victory_A,Oil,No

In [9]:
df.describe()

,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Air_Strikes,Naval_Battles
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1987.338000,1003.734667,24423.385000,24959.623333,2489.252000,98.849667
std,21.766006,568.221869,14129.940099,14345.873994,1448.823011,58.377493
min,1950.000000,2.000000,105.000000,119.000000,0.000000,0.000000
25%,1968.000000,529.000000,12292.000000,12768.250000,1228.750000,47.000000
50%,1987.000000,999.000000,23889.000000,24270.000000,2457.000000,99.000000
75%,2007.000000,1493.000000,36801.000000,37424.500000,3738.250000,151.000000
max,2024.000000,1999.000000,49995.000000,49992.000000,4999.000000,199.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country_A          3000 non-null   str
 1   Country_B          3000 non-null   str
 2   Conflict_Type      3000 non-null   str
 3   Year               3000 non-null   int64
 4   Duration_Days      3000 non-null   int64
 5   Military_Deaths_A  3000 non-null   int64
 6   Military_Deaths_B  3000 non-null   int64
 7   Alliance_A         2017 non-null   str
 8   Alliance_B         2008 non-null   str
 9   Weapons_Used       3000 non-null   str
 10  Air_Strikes        3000 non-null   int64
 11  Naval_Battles      3000 non-null   int64
 12  Sanctions          3000 non-null   str
 13  Ceasefire          3000 non-null   str
 14  Outcome            3000 non-null   str
 15  Resource_Dispute   2255 non-null   str
 16  UN_Involvement     3000 non-null   str
dtypes: int64(6), str(11)
memory usage: 398.6 KB

In [16]:
df.dtypes

Country_A              str
Country_B              str
Conflict_Type          str
Year                 int64
Duration_Days        int64
Military_Deaths_A    int64
Military_Deaths_B    int64
Alliance_A             str
Alliance_B             str
Weapons_Used           str
Air_Strikes          int64
Naval_Battles        int64
Sanctions              str
Ceasefire              str
Outcome                str
Resource_Dispute       str
UN_Involvement         str
dtype: object

In [17]:
df.head()

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Alliance_A,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,NATO,Regional,Mixed,87,104,Yes,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,NATO,NATO,Conventional,1529,87,Yes,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,Regional,NaN,Nuclear,3239,9,No,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,NaN,NATO,Cyber,3185,15,No,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,Regional,NATO,Mixed,12,22,Yes,No,Victory_A,Land,No

In [18]:
df = df.convert_dtypes()

In [19]:
df.to_parquet('global_conflicts_dataset.parquet', index=False)

ArrowKeyError: A type extension with name pandas.period already defined

In [20]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str)

In [21]:
df.to_parquet('global_conflicts_dataset.parquet', index=False)

ArrowKeyError: A type extension with name pandas.period already defined

In [22]:
for col in df.columns:
    try:
        df[[col]].to_parquet('teste.parquet')
    except Exception as e:
        print(col, e)

Country_A A type extension with name pandas.period already defined
Country_B A type extension with name pandas.period already defined
Conflict_Type A type extension with name pandas.period already defined
Year A type extension with name pandas.period already defined
Duration_Days A type extension with name pandas.period already defined
Military_Deaths_A A type extension with name pandas.period already defined
Military_Deaths_B A type extension with name pandas.period already defined
Alliance_A A type extension with name pandas.period already defined
Alliance_B A type extension with name pandas.period already defined
Weapons_Used A type extension with name pandas.period already defined
Air_Strikes A type extension with name pandas.period already defined
Naval_Battles A type extension with name pandas.period already defined
Sanctions A type extension with name pandas.period already defined
Ceasefire A type extension with name pandas.period already defined
Outcome A type extension with name pandas.period already defined
Resource_Dispute A type extension with name pandas.period already defined
UN_Involvement A type extension with name pandas.period already defined

In [23]:
for col in df.select_dtypes(include='object').columns:
   df[col] = df[col].fillna('').astype(str)

In [24]:
df.to_parquet('global_conflicts_dataset.parquet', index=False)

ArrowKeyError: A type extension with name pandas.period already defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('global_conflicts_dataset.csv')
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,Civilian_Deaths,Economic_Loss_USD_Billions,Temperature_Avg_C,...,Naval_Battles,Sanctions,Refugees_Millions,Ceasefire,Outcome,Latitude,Longitude,Climate_Zone,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,50364,176.45,8.2,...,104,Yes,6.68,No,Victory_A,88.811,101.020,Temperate,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,176846,435.83,24.8,...,87,Yes,14.51,Yes,Stalemate,55.878,78.502,Polar,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,17280,154.50,17.3,...,9,No,1.63,No,Stalemate,29.263,144.680,Tropical,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,92279,273.20,12.3,...,15,No,7.23,No,Victory_A,-22.281,-147.397,Polar,Water,No
4,Australia,France,War,2012,753,29149,40672,72545,351.35,31.1,...,22,Yes,19.65,No,Victory_A,17.638,169.360,Temperate,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,23016,465.44,4.1,...,162,Yes,10.62,No,Victory_A,71.175,36.407,Polar,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,175145,265.39,7.9,...,2,No,5.12,Yes,Victory_B,-42.396,-0.958,Polar,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,11370,461.47,21.5,...,32,No,2.47,No,Victory_A,-29.783,19.301,Arid,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,188963,103.94,31.2,...,6,No,7.26,No,Victory_A,81.474,42.923,Arid,NaN,No
2999,Israel,India,War,1999,285,20549,30400,65175,302.32,-6.1,...,104,Yes,8.58,Yes,Victory_A,-78.367,65.547,Arid,Oil,No

In [4]:
df = df.drop(columns=['Civilian_Deaths', 'Rainfall_mm', 'Terrain_Type', 'Refugees_Millions', 'Population_A_Millions', 'Population_B_Millions', 'GDP_A_Billions', 'Temperature_Avg_C','Economic_Loss_USD_Billions', 'Temperature_Avg_C', 'Latitude', 'Longitude', 'Climate_Zone'])
df

,Country_A,Country_B,Conflict_Type,Year,Duration_Days,Military_Deaths_A,Military_Deaths_B,GDP_B_Billions,Alliance_A,Alliance_B,Weapons_Used,Air_Strikes,Naval_Battles,Sanctions,Ceasefire,Outcome,Resource_Dispute,UN_Involvement
0,France,France,Cold Conflict,2020,1829,33197,41305,15609.5,NATO,Regional,Mixed,87,104,Yes,No,Victory_A,Land,Yes
1,India,Japan,Cold Conflict,2013,1234,26773,10526,12932.3,NATO,NATO,Conventional,1529,87,Yes,Yes,Stalemate,Water,No
2,Israel,USA,Civil War,1970,1982,17256,7604,22137.4,Regional,NaN,Nuclear,3239,9,No,No,Stalemate,Water,No
3,Turkey,Australia,Proxy War,2021,1754,1745,33468,10539.7,NaN,NATO,Cyber,3185,15,No,No,Victory_A,Water,No
4,Australia,France,War,2012,753,29149,40672,14095.4,Regional,NATO,Mixed,12,22,Yes,No,Victory_A,Land,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,China,France,Skirmish,1980,395,4452,45602,12922.5,Regional,NATO,Mixed,2073,162,Yes,No,Victory_A,Oil,Yes
2996,Russia,Russia,Cold Conflict,2009,300,284,627,22966.5,Regional,Regional,Conventional,3077,2,No,Yes,Victory_B,Oil,No
2997,Canada,Israel,War,2019,1550,10484,3022,4743.8,Regional,Regional,Mixed,3212,32,No,No,Victory_A,Land,Yes
2998,Germany,Turkey,Cold Conflict,1966,749,14419,5949,3134.9,Regional,Regional,Cyber,3813,6,No,No,Victory_A,NaN,No
2999,Israel,India,War,1999,285,20549,30400,6039.6,NATO,NaN,Conventional,1050,104,Yes,Yes,Victory_A,Oil,No

In [5]:
df.to_parquet('global_conflicts_dataset.parquet', index=False)

In [7]:
df.to_excel('global_conflicts_dataset.xlsx', index=False)